### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by freebob** [predsci/POT3D#13]
I would like to inquire about how the br_inpt.h5 file in the model is processed or generated. I noticed that websites such as GONG provide the data in FITS format, and I am wondering if there is a specific program or method to convert the FITS files into the h5 format used here.

Could you please provide some insights on this process or share any related tools or scripts?

**Comment by sumseq** [comment]
You can see some example input maps in the "run_examples" folder.   
A description of the grid the maps use can be found in our HipFT code's documentation here:  https://github.com/predsci/HipFT/blob/main/doc/hipft_grid.png 
Note that POT3D expects the map data to be stride-1 in the theta direction (theta-phi), while the HipFT maps are in phi-theta.

As for converting FITS files, we do not currently have an open-source tool for that at the moment.
There are subtle issues involved in the conversion as the FITS header information needs to be used to create proper co-latitude (theta) and longitude scale values for the h5 file.  Often FITS files are in sine-latitude, so an interpolation may be needed after assigning scales.  Additionally, some data sets do not have polar data, so that needs to be filled, and the resulting map may need to be flux balanced.

You are welcome to follow our Open-source Flux Transport repository (github.com/predsci/oft) which contains some of our map processing capabilities.   It is possible that some FITS conversion scripts may be added to that package in the future.
